=== raftario/BSIPA-MetadataFileSchema/Schema.json
{
  "definitions": {
    "semver": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    },
    "verrange": {
      "type": "string",
      "pattern": "^(?:[~\\^*]=?)?(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?(?:-(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)?"
    },
    "url": {
      "type": "string",
      "pattern": "https?://(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,}(/[-a-zA-Z0-9@:%_\\+.~#?&//=]*)?"
    },
    "id": {
      "type": "string",
      "pattern": "^([A-Z][0-9a-z]*)+(\\.([A-Z][0-9a-z]*)+)*$"
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "title": "root",
  "required": [
    "id",
    "name",
    "version",
    "gameVersion",
    "description",
    "author",
    "license"
  ],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "$ref": "#/definitions/id",
      "title": "Mod ID",
      "description": "Unique ID used my BeatMods2 and other mods to identify this mod"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "Mod Name",
      "pattern": "^[^\\n\\r\\t]+$"
    },
    "version": {
      "$id": "#/properties/version",
      "$ref": "#/definitions/semver",
      "title": "Mod Version",
      "description": "Version according to the semantic versioning specification"
    },
    "gameVersion": {
      "$id": "#/properties/gameVersion",
      "type": "string",
      "title": "Game Version",
      "description": "Beat Saber version this mod was designed for"
    },
    "description": {
      "$id": "#/properties/description",
      "type": "array",
      "title": "Mod Description",
      "items": {
        "type": "string",
        "pattern": "^[^\\n\\r]*$"
      }
    },
    "author": {
      "$id": "#/properties/author",
      "type": "string",
      "title": "Mod Author"
    },
    "license": {
      "$id": "#/properties/license",
      "type": "string",
      "title": "Mod License",
      "description": "SPDX license expression (or \"FILE licensefilehere\" if not a valid SPDX license)"
    },
    "dependsOn": {
      "$id": "#/properties/dependsOn",
      "type": "object",
      "title": "Dependencies",
      "description": "Other mods this mod depends on mapped by ID",
      "patternProperties": {
        "^([A-Z][0-9a-z]*)+(\\.([A-Z][0-9a-z]*)+)*$": {
          "$ref": "#/definitions/verrange",
          "description": "Version range according to the semantic versioning specification"
        }
      }
    },
    "conflictsWith": {
      "$id": "#/properties/conflictsWith",
      "type": "object",
      "title": "Incompatibilities",
      "description": "Other mods this mod conflicts with mapped by ID",
      "patternProperties": {
        "^([A-Z][0-9a-z]*)+(\\.([A-Z][0-9a-z]*)+)*$": {
          "$ref": "#/definitions/verrange",
          "description": "Version range according to the semantic versioning specification"
        }
      }
    },
    "loadAfter": {
      "$id": "#/properties/loadAfter",
      "type": "array",
      "description": "Mods to load before this one",
      "items": {
        "$ref": "#/definitions/id",
        "description": "Mod ID"
      },
      "uniqueItems": true
    },
    "loadBefore": {
      "$id": "#/properties/loadBefore",
      "type": "array",
      "description": "Mods to load after this one",
      "items": {
        "$ref": "#/definitions/id",
        "description": "Mod ID"
      },
      "uniqueItems": true
    },
    "features": {
      "$id": "#/properties/features",
      "type": "array",
      "title": "Mod Features",
      "description": "Features to enable for this mod",
      "items": {
        "type": "string",
        "description": "Feature name"
      },
      "uniqueItems": true
    },
    "icon": {
      "$id": "#/properties/icon",
      "type": "string",
      "title": "Mod Icon",
      "description": "Path to a PNG icon for this mod",
      "pattern": ".*\\.png"
    },
    "links": {
      "$id": "#/properties/links",
      "type": "object",
      "title": "Links",
      "description": "Links associated with this mod",
      "properties": {
        "project-home": {
          "$id": "#/properties/links/properties/project-home",
          "$ref": "#/definitions/url",
          "title": "Home",
          "description": "Link to the mod homepage (same as project-source if not specified)"
        },
        "project-source": {
          "$id": "#/properties/links/properties/project-source",
          "$ref": "#/definitions/url",
          "title": "Source",
          "desccription": "Link to the mod source (same as project-home if not specified)"
        },
        "donate": {
          "$id": "#/properties/links/properties/donate",
          "$ref": "#/definitions/url",
          "title": "Donation",
          "description": "Link to a donation page"
        }
      }
    },
    "publish": {
      "$id": "#/properties/publish",
      "type": "object",
      "title": "Publishing Settings",
      "description": "Settings to use when publishing this mod using bm2",
      "properties": {
        "script": {
          "$id": "#/properties/publish/properties/script",
          "type": "array",
          "title": "Publishing Script",
          "description": "Commands to run before publishing (cwd will be the manifest directory) (will run even if resource is not specified)",
          "items": {
            "type": "string",
            "description": "Command"
          }
        },
        "resource": {
          "$id": "#/properties/publish/properties/resource",
          "type": "string",
          "title": "Resource",
          "description": "Path to the resource to upload to BeatMods2 (if it is a file, will be uploaded directly; if it is a folder, zipped contents will be uploaded)"
        }
      }
    },
    "readme": {
      "$id": "#/properties/readme",
      "type": "string",
      "title": "Readme",
      "description": " Path to a markdown readme to display on BeatMods2 (same as description if not specified)"
    }
  }
}

=== raftario/BSIPA-MetadataFileSchema/Example.json
{
  "$schema": "https://raw.githubusercontent.com/raftario/BSIPA-MetadataFileSchema/master/Schema.json",
  "name": "Example Mod",
  "id": "ExampleMod",
  "description": [
    "This is an example mod.",
    "",
    "It has a multiline description."
  ],
  "version": "1.2.3",
  "gameVersion": "0.13.2",
  "author": "DaNike",
  "license": "MIT",
  "dependsOn": {
    "SongCore": "^2.5.1"
  },
  "conflictsWith": {
    "CameraPlus": "^3.5.7"
  },
  "loadAfter": ["SongCore"],
  "loadBefore": ["ScoreSaber"],
  "features": [],
  "links": {
    "project-source": "https://github.com/raftario/BSIPA-MetadataFileSchema/blob/master/Schema.json",
    "project-home": "https://github.com/raftario/BSIPA-MetadataFileSchema/blob/master/Example.json"
  },
  "publish": {
    "script": ["msbuild ExampleMod/ExampleMod.csproj"],
    "resource": "ExampleMod/bin/"
  },
  "readme": "README.md",
  "icon": "ExampleMod/icon.png"
}
